store/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^tos/$', views.tos, name='tos'),
    url(r'^checkout/$', views.checkout, name='checkout'),
]

succulent_surprise_service/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('store.urls')),
    url(r'^admin/', admin.site.urls),
]

store/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

class Order(models.Model):
    STATES = (('S', 'Submitted'), ('P', 'Paid'),
              ('D', 'Dispatched'), ('E', 'Error'))

    updated_at = models.DateTimeField('Date created')
    state = models.CharField(max_length=1, choices=STATES, blank=True)

    stripe_tx = models.CharField('Stripe tx', max_length=100)

    from_first_name = models.CharField('Sender first name', max_length=60)
    from_last_name = models.CharField('Sender last name', max_length=60)
    from_email = models.CharField('Sender email', max_length=100)

    to_first_name = models.CharField('Recipient first name', max_length=60)
    to_last_name = models.CharField('Recipient last name', max_length=60)

    delivery_company_name = models.CharField('Company name', max_length=60, blank=True)
    delivery_first = models.CharField('Address line 1', max_length=100)
    delivery_second = models.CharField('Address line 2', max_length=100, blank=True)
    delivery_third = models.CharField('Address line 3', max_length=100, blank=True)
    delivery_postcode = models.CharField('Postcode', max_length=10)
    delivery_note = models.CharField('Gift note', max_length=200, blank=True)

    def save(self, *args, **kwargs):
        self.updated_at = timezone.now()
        return super(Order, self).save(*args, **kwargs)

    def __str__(self):
        return "[ %s ] %s %s for %s %s - %s" % (self.get_state_display(),
                                                self.from_first_name, self.from_last_name,
                                                self.to_first_name, self.to_last_name,
                                                self.delivery_postcode)

store/views.py
import os

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.edit import CreateView, ModelFormMixin
from django.forms import Form, ModelForm

import stripe

from store.models import Order

stripe.api_key = os.environ['STRIPE_API_KEY']

class CheckoutForm(ModelForm):
    class Meta:
        model = Order
        fields = ['from_first_name', 'from_last_name',
                  'to_first_name', 'to_last_name',
                  'delivery_company_name', 'delivery_first', 'delivery_second',
                  'delivery_third', 'delivery_postcode', 'delivery_note']

def process_payment(stripe_email, stripe_token, form):
    order = Order(state='S',
                  from_first_name=form.cleaned_data['from_first_name'],
                  from_last_name=form.cleaned_data['from_last_name'],
                  from_email=stripe_email,
                  stripe_tx=stripe_token,
                  to_first_name=form.cleaned_data['to_first_name'],
                  to_last_name=form.cleaned_data['to_last_name'],
                  delivery_company_name=form.cleaned_data['delivery_company_name'],
                  delivery_first=form.cleaned_data['delivery_first'],
                  delivery_second=form.cleaned_data['delivery_second'],
                  delivery_third=form.cleaned_data['delivery_third'],
                  delivery_postcode=form.cleaned_data['delivery_postcode'],
                  delivery_note=form.cleaned_data['delivery_note'],)

    try:
        # Create a charge: this will charge the user's card
        charge = stripe.Charge.create(amount=1600,
                                      currency='gbp',
                                      source=stripe_token,
                                      description='One succulent surprise')

        order.state = 'P'
    except stripe.error.CardError as e:
        # The card has been declined
        order.state = 'E'
    finally:
        order.save()

    return order

def checkout(request):
    if request.method != 'POST':
        form = CheckoutForm()

    if request.method == 'POST':
        form = CheckoutForm(request.POST)

        if form.is_valid():
            stripe_email = request.POST['stripeEmail'],
            stripe_token = request.POST['stripeToken'],
            order = process_payment(stripe_email[0], stripe_token[0], form)

            if order.state == 'P':
                return HttpResponseRedirect('/thanks/')

    return render(request, 'store/order_form.html', {'form': form})

def index(request):
    return render(request, 'store/index.html')

def thanks(request):
    return render(request, 'store/thanks.html')

def tos(request):
    return render(request, 'store/tos.html')

store/templates/store/base.html
<html lang="en">
  <title>Succulent Surprise</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@succiesurprise">
  <meta name="twitter:creator" content="@succiesurprise">
  <meta name="twitter:title" content="Make a Succulent Surprise">
  <meta name="twitter:description" content="Super succulents in tiny tumblers!">
  <meta name="twitter:image" content="https://succulentsurprise.com/static/store/banter.1.jpg">
  <meta property="og:url" content="https://succulentsurprise.com"/>
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="Succulent Surprise"/>
  <meta property="og:description" content="Super succulents in tiny tumblers!"/>
  <meta property="og:image" content="https://succulentsurprise.com/static/store/banter.1.jpg"/>
  <link rel="stylesheet" href="https://unpkg.com/tachyons/css/tachyons.min.css">
  <link rel="stylesheet" href="/static/store/twemoji-awesome.css">
  <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
  <style>
    .ranga {
      font-family: 'Courgette', cursive;
      text-rendering: geometricPrecision;
    }
    .text-shadow {
      text-shadow: 2px 2px 0px white;
    }
    .no-visited:visited {
      color: inherit;
    }
    .pad-children > * {
        margin: 0px .5em 0px .5em;
    }
    .rotate-30deg {
      transform: rotate(-30deg);
    }
    .animate {
      transition: all .3s ease-in;
    }
    .start {
      opacity: 0.5;
      color: darkgreen;
    }
    .end {
      opacity: 0.7;
      color: coral;
    }
  </style>

  <body class="w-100 bg-near-white">
    {% block header %}{% endblock %}
    {% block content %}{% endblock %}

    <footer class="pv4 ph3 ph5-m ph6-l mid-gray">
      <div class="center tc pv5">
        <a class="link near-black hover-dark-green dib h2 w2 mr3" href="https://www.facebook.com/SuccieSurprise/" title="Facebook"><i class="fa fa-2x fa-facebook-official" aria-hidden="true"></i></a>
        <a class="link near-black hover-dark-green dib h2 w2 mr3" href="https://instagram.com/succiesurprise" title="Instagram"><i class="fa fa-2x fa-instagram" aria-hidden="true"></i></a>
        <a class="link near-black hover-dark-green dib h2 w2 mr3" href="https://twitter.com/succiesurprise" title="Twitter"><i class="fa fa-2x fa-twitter-square aria-hidden="true"></i></a>
      </div>
      <small class="f6 db tc">© 2016 <b class="ttu">Succulent Surprise</b>, All Rights Reserved</small>
      <div class="tc mt3">
        <a href="/tos#tos" title="Terms" class="f6 dib ph2 link mid-gray dim">Terms</a>
        <a href="/tos#privacy" title="Privacy" class="f6 dib ph2 link mid-gray dim">Privacy</a>
      </div>
    </footer>

    <script type="text/javascript">
      var changeFunnyText = (function () {
        var funnyTextEl = document.getElementById('funny-placeholder')
        var funnyTexts = ['mum', 'bae', 'sister', 'crush', 'brother',
                          'granny', 'tinder date', 'self', 'dad', 'boss',
                          'bff'];
        var index = 0;

        if (funnyTextEl) {
          return function () {
            funnyTextEl.classList.toggle('start');
            funnyTextEl.innerText = funnyTexts[index];
            index = (index + 1) % funnyTexts.length;
            funnyTextEl.classList.toggle('end');
          }
        }

        return function () { };
      })

      var paintCanvas = (function () {
        var canvas = document.getElementById('paint-job')
        if (!canvas) { return; }

        var ctx = canvas.getContext('2d')
        var W = Math.min(600, window.innerWidth)

        canvas.width = window.innerWidth
        ctx.lineWidth = 6;
        ctx.fillStyle = "gold";
        ctx.beginPath();

        var o = 0
        if (W === 600) {
          o = window.innerWidth / 2 - 300
        }

        ctx.moveTo(o, 0);
        ctx.quadraticCurveTo(o + W / 4, 60, o + W / 2, 0);
        ctx.quadraticCurveTo(o + W / 2 + W / 8, 40, o + W - W / 4, 0);
        ctx.quadraticCurveTo(o + W - W / 8, 40, o + W, 0);
        ctx.fill();
      })

      window.setInterval(changeFunnyText(), 2000)
      paintCanvas()
    </script>

    <script>window.twttr = (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0],
        t = window.twttr || {};
      if (d.getElementById(id)) return t;
      js = d.createElement(s);
      js.id = id;
      js.src = "https://platform.twitter.com/widgets.js";
      fjs.parentNode.insertBefore(js, fjs);

      t._e = [];
      t.ready = function(f) {
        t._e.push(f);
      };

      return t;
    }(document, "script", "twitter-wjs"));</script>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-88644685-1', 'auto');
      ga('send', 'pageview');

    </script>

    <script src="https://use.fontawesome.com/712b69cf0d.js"></script>
  </body>
</html>

store/templates/store/index.html
{% extends "store/base.html" %}

{% load static %}

{% block header %}
    <header class="tc pv6 ph3 bg-yellow">
      <h1 class="ranga f1 f-headline-ns text-shadow lh-solid rotate-30deg o-80">Succulent<br/>Surprise</h1>
    </header>

    <div class="w-100 overflow-hidden">
      <canvas id="paint-job" width="100%" height="50px"/>
    </div>
{% endblock %}

{% block content %}
    <section class="ph3 ph5-ns cf m0 sans-serif">
      <div class="tc center">
        <img class="fit w-25 center" src="{% static "store/plant.svg" %}"/>
      </div>
      <p class="f2 tc center measure-narrow lh-copy">Send your&nbsp;<span id="funny-placeholder" class="dib start animate b">self</span><br/> a super succulent in a tiny tumbler!</p>
      <p class="f3 i serif tc center measure-narrow lh-copy">For only £16 we select a succie, pick a pot and pop it in the post.</p>
    </section>

    <section class="ph3 cf mt0 sans-serif tc pv4 pv5-ns">
      <a href="{% url 'checkout' %}" class="f3 dib ba b--black-20 bg-green near-white ph4 pv3 br2 link dim no-underline">Order now!</a>
    </section>

    <section class="ph3 ph5-ns pv3 cf mt0 sans-serif w-75-ns center">
      <!--<h2 class="f3 fw4 ph3-ns mb0">Shipped succulents so far!</h2>-->
      <div class="w-100 cf pt3 pa3-ns">
        <div class="fl w-100 w-33-ns ph0 pv1 pa1-ns">
          <img class="w-100 db outline black-10" src="{% static "store/a.jpg" %}"/>
        </div>
        <div class="fl w-100 w-33-ns ph0 pv1 pa1-ns">
          <img class="w-100 db outline black-10" src="{% static "store/b.jpg" %}"/>
        </div>
        <div class="fl w-100 w-33-ns ph0 pv1 pa1-ns">
          <img class="w-100 db outline black-10" src="{% static "store/c.jpg" %}"/>
        </div>
      </div>
    </section>

    <section class="ph3 ph5-ns pv3 cf mt0 sans-serif w-75-ns center">
      <h2 class="f3 fw4 ph3-ns mb0">Taking care of your babies</h2>
      <div class="w-100 cf pt3 pa3-ns">
        <p>Our succies are a lucky dip of Echeveria, Aeonium, Crassula and Sedum varieties. To keep them happy, find a well lit spot.</p>
        <p>Give them a teaspoon of water to drink every week or so. They don't like wet feet, so don't over do it! Water less in winter, when they're sleeping.</p>
        <p>These little guys are 5cm babies. Re-pot them once they get too big for their boots!</p>
      </div>
    </section>

    <section class="ph3 ph5-ns pv3 cf mt0 sans-serif w-75-ns center">
      <h2 class="f3 fw4 ph3-ns mb0">Shipped succulents so far!</h2>
      <div class="w-100 cf pt3 pa3-ns">
        <div class="fl w-100 w-33-ns ph0 pv1 pa1-ns">
          <img class="w-100 db outline black-10" src="{% static "store/d.jpg" %}"/>
        </div>
        <div class="fl w-100 w-33-ns ph0 pv1 pa1-ns">
          <img class="w-100 db outline black-10" src="{% static "store/e.jpg" %}"/>
        </div>
        <div class="fl w-100 w-33-ns ph0 pv1 pa1-ns">
          <img class="w-100 db outline black-10" src="{% static "store/f.jpg" %}"/>
        </div>
      </div>
    </section>

{% endblock %}

store/templates/store/order_form.html
{% extends "store/base.html" %}

{% load static %}

{% block header %}
    <a href="{% url 'index' %}" class="no-underline no-visited pointer">
      <header class="tc pv4 ph3 bg-yellow">
        <h1 class="ranga f1 text-shadow lh-solid rotate-30deg o-80">Succulent<br/>Surprise</h1>
      </header>

      <div class="w-100 overflow-hidden">
        <canvas id="paint-job" width="100%" height="50px"/>
      </div>
    </a>
{% endblock %}


{% block content %}
<div class="mw6 center ma4">
  <form action="{% url 'checkout' %}" method="POST">
    {% csrf_token %}

    <h2 class="f2 fw1 cf tc">Order</h2>

    <div class="cf f6 lh-copy measure-narrow light-grey tc center">
        <p>UK delivery only. Succies are sent first class and should be with you in a day or two.</p>
    </div>

    {% if form.errors %}
        <div class="cf f6 lh-copy light-red tc">
            <p>There is some missing information&hellip; Please check the form again.</p>
        </div>
    {% endif %}

    <h3 class="f4 f3-ns fw1 cf ph2">Your Info</h3>

    <div class="cf">
      <div class="fl w-50 pa2">
        <label class="f6 f5-ns fw1 cf db mv1" for="id_from_first_name">First Name</label>
        <input class="w-100 pa2 input-reset hover-green ba b--dark-green" id="id_from_first_name" maxlength="60" name="from_first_name" type="text" required="" value="{{ form.from_first_name.value|default:'' }}">
        {{ form.from_first_name.errors }}
      </div>

      <div class="fl w-50 pa2">
        <label class="f6 f5-ns fw1 cf db mv1" for="id_from_last_name">Last Name</label>
        <input class="w-100 pa2 input-reset hover-green ba b--dark-green" id="id_from_last_name" maxlength="60" name="from_last_name" type="text" required="" value="{{ form.from_last_name.value|default:'' }}">
        {{ form.from_last_name.errors }}
      </div>
    </div>

    <h3 class="f4 f3-ns fw1 cf ph2">Delivery</h3>

    <div class="cf">
      <div class="fl w-50 pa2">
        <label class="f6 f5-ns fw1 cf db mv1" for="id_to_first_name">First Name</label>
        <input class="w-100 pa2 input-reset hover-green ba b--dark-green" id="id_to_first_name" maxlength="60" name="to_first_name" type="text" required="" value="{{ form.to_first_name.value|default:'' }}">
        {{ form.to_first_name.errors }}
      </div>

      <div class="fl w-50 pa2">
        <label class="f6 f5-ns fw1 cf db mv1" for="id_to_last_name">Last Name</label>
        <input class="w-100 pa2 input-reset hover-green ba b--dark-green" id="id_to_last_name" maxlength="60" name="to_last_name" type="text" required="" value="{{ form.to_last_name.value|default:'' }}">
        {{ form.to_last_name.errors }}
      </div>
    </div>

    <div class="cf">
      <div class="fl w-100 pa2">
        <label class="f6 f5-ns fw1 cf db mv1" for="id_delivery_company_name">Company Name (optional)</label>
        <input class="w-100 pa2 input-reset hover-green ba b--dark-green" id="id_delivery_company_name" maxlength="60" name="delivery_company_name" type="text" value="{{ form.delivery_company_name.value|default:'' }}">
        {{ form.delivery_company_name.errors }}
      </div>
    </div>

    <div class="cf">
      <div class="fl w-100 pa2">
        <label class="f6 f5-ns fw1 cf db mv1" for="id_delivery_first">Address Line 1</label>
        <input class="w-100 pa2 input-reset hover-green ba b--dark-green" id="id_delivery_first" maxlength="60" name="delivery_first" type="text" required="" value="{{ form.delivery_first.value|default:'' }}">
        {{ form.delivery_first.errors }}
      </div>
    </div>

    <div class="cf">
      <div class="fl w-100 pa2">
        <label class="f6 f5-ns fw1 cf db mv1" for="id_delivery_second">Address Line 2 (optional)</label>
        <input class="w-100 pa2 input-reset hover-green ba b--dark-green" id="id_delivery_second" maxlength="60" name="delivery_second" type="text" value="{{ form.delivery_second.value|default:'' }}">
        {{ form.delivery_second.errors }}
      </div>
    </div>

    <div class="cf">
      <div class="fl w-100 pa2">
        <label class="f6 f5-ns fw1 cf db mv1" for="id_delivery_thirs">Address Line 3 (optional)</label>
        <input class="w-100 pa2 input-reset hover-green ba b--dark-green" id="id_delivery_third" maxlength="60" name="delivery_third" type="text" value="{{ form.delivery_third.value|default:'' }}">
        {{ form.delivery_third.errors }}
      </div>
    </div>

    <div class="cf">
      <div class="fl w-50 pa2">
        <label class="f6 f5-ns fw1 cf db mv1" for="id_delivery_postcode">Postcode</label>
        <input class="w-100 pa2 input-reset hover-green ba b--dark-green" id="id_delivery_postcode" maxlength="10" name="delivery_postcode" type="text" required="" value="{{ form.delivery_postcode.value|default:'' }}">
        {{ form.delivery_postcode.errors }}
      </div>
      <div class="fl w-50 pa2">
        <label class="f6 f5-ns fw1 cf db mv1" for="id_delivery_country">Country</label>
        <input class="w-100 pa2 input-reset hover-green ba b--dark-green" id="id_delivery_country" maxlength="6" name="delivery_country" type="text" value="United Kingdom" disabled="true">
      </div>
    </div>

    <div class="cf">
      <div class="fl w-100 pa2">
        <label class="f6 f5-ns fw1 cf db mv1" for="id_delivery_note">Optional handwritten note! (make it fit in a Tweet!)</label>
        <input class="w-100 pa4 input-reset hover-green ba b--dark-green" id="id_delivery_note" maxlength="140" name="delivery_note" type="text" value="{{ form.delivery_note.value|default:'' }}">
        {{ form.delivery_note.errors }}
      </div>
    </div>

    <div class="cf">
      <div class="fl w-100 pa2">
        <label class="pa0 ma0 lh-copy f6 pointer"><input type="checkbox" name="tos" required=""> I agree to the term and conditions</label>
      </div>
    </div>

    <div class="mv4 tc">
      <div class="fl w-100 pa2">
        <a class="fw1">One succulent surprise £16</a>
      </div>
      <script
        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="pk_live_rTIlcBZ6fbuRGTMr9qOcERvY"
        data-amount="1600"
        data-image="{% static "store/plant.png" %}"
        data-name="Succulent Surprise"
        data-description="1 succulent and a pot"
        data-locale="auto"
        data-zip-code="true"
        data-allow-remember-me="false"
        data-currency="GBP">
      </script>
    </div>
  </form>
</div>
{% endblock %}

store/templates/store/thanks.html
{% extends "store/base.html" %}

{% load static %}

{% block header %}
    <a href="{% url 'index' %}" class="no-underline no-visited pointer">
      <header class="tc pv4 ph3 bg-yellow">
        <h1 class="ranga f1 text-shadow lh-solid rotate-30deg o-80">Succulent<br/>Surprise</h1>
      </header>

      <div class="w-100 overflow-hidden">
        <canvas id="paint-job" width="100%" height="50px"/>
      </div>
    </a>
{% endblock %}


{% block content %}
    <div class="mw6 center ma4">
        <h2 class="f-subheadline lh-title cf tc fw1 i dark-green">Thanks!</h2>

        <p class="f4 lh-copy tc">Your order is on the way! We are potting, packing and posting as hard as we can to deliver your surprise. xoxoxo</p>

        <p class="f4 lh-copy tc">In the meantime why not help us send even more love out into the world! <i class="twa twa-hatching-chick"></i> <i class="twa twa-heart"></i></p> 

        <div class="flex flex-row pad-children justify-center items-center pv4">
          <a class="twitter-share-button"
           href="https://twitter.com/intent/tweet?text=Love%20succulents!%20@succiesurprise&url=https://succulentsurprise.com"
           data-size="large">Tweet</a>

          <div class="fb-share-button" data-href="https://succulentsurprise.com" data-layout="button" data-size="large" data-mobile-iframe="false"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fsucculentsurprise.com%2F&amp;src=sdkpreparse">Share</a></div>

          <style>.ig-b- { display: inline-block; }
.ig-b- img { visibility: hidden; }
.ig-b-:hover { background-position: 0 -60px; } .ig-b-:active { background-position: 0 -120px; }
.ig-b-v-24 { width: 137px; height: 24px; background: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24.png) no-repeat 0 0; }
@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
.ig-b-v-24 { background-image: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24@2x.png); background-size: 160px 178px; } }</style>
<a href="https://www.instagram.com/succiesurprise/?ref=badge" class="ig-b- ig-b-v-24"><img src="//badges.instagram.com/static/images/ig-badge-view-24.png" alt="Instagram" /></a>
        </div>
    </div>
{% endblock %}

store/templates/store/tos.html
{% extends "store/base.html" %}

{% load static %}

{% block header %}
    <a href="{% url 'index' %}" class="no-underline no-visited pointer">
      <header class="tc pv4 ph3 bg-yellow">
        <h1 class="ranga f1 text-shadow lh-solid rotate-30deg o-80">Succulent<br/>Surprise</h1>
      </header>

      <div class="w-100 overflow-hidden">
        <canvas id="paint-job" width="100%" height="50px"/>
      </div>
    </a>
{% endblock %}


{% block content %}
    <div id="tos" class="mw6 center ma4">
        <h2 class="f2 fw1">Terms and Conditions</h2>
        <h3 class="f3 fw1">Product</h3>
        <p class="measure">Our mini tumblers are sourced from Falcon Enamelware. There are five colours available: coal black, pigeon grey, pillarbox red, white with a blue rim, and beige with a grey rim. Some variation in colour or glaze can occur - it just makes them more unique!</p>
        <p>All our succulents are picked from a mix of Echeveria, Aeonium, Crassula and Sedum varieties. Internal plastic pots are 5 centimetres in diameter, but plants may vary slightly in size. Pictures on the website are for illustration only. Stock varies according to availability from our suppliers.</p>
        <h3 class="f3 fw1">Delivery</h3>
        <p class="measure">Once we have taken your order, we pack and dispatch by 4pm each day. All packages are sent by First Class post. Deliveries should arrive within two days, but we cannot guarantee next day delivery, especially at busy times of the year. We cannot provide delivery slots. Please ensure you provide all the details needed for the package to reach the recipient, especially if sending to a large office or via a mail room. We can only deliver within the UK.</p>
        <h3 class="f3 fw1">Packaging</h3>
        <p class="measure">Our succulents are boxed in sustainable FSC cardboard - please recycle after use! They are cushioned with eco-friendly wood wool. Succulents will occasionally lose a few leaves in transit - don’t worry! Just give them drink and they should perk up.</p>
        <h3 class="f3 fw1">Exchanges</h3>
        <p class="measure">We aim to get your succies to you in tip-top condition. If your succulent arrives looking sad or battered, just let us know and we’ll send you a new one. We ask that you send us a photo of any damage if possible, so we can improve our packaging!</p>
        <h3 class="f3 fw1">Refunds</h3>
        <p class="measure">If you’re not delighted with your surprise, just contact us within 30 days to arrange return and refund. We cannot offer refunds after more than 30 days. Unfortunately, we cannot cover shipping costs for returns.</p>
    </div>
    <div id="privacy" class="mw6 center ma4">
        <h2 class="f2 fw1">Privacy</h2>
        <p class="measure">We do not store credit card details nor do we share customer details with any third parties.</p>
        <p class="measure">All transactions are conducted over HTTPS. Our payment provider is Stripe.</p>
        <p class="measure">We use Google Analytics, which uses cookies to track visitor usage.</p>
    </div>
{% endblock %}